"""Static TFT **Set 17** reference data used for synthetic ingestion and entity naming.

Champions, items, augments and traits are the real Set 17 roster pulled from
Riot's Community Dragon data, with real icon URLs served from the public CDN.
Match statistics themselves are generated (synthetic mode) over this real roster
so the full pipeline runs end-to-end without a live Riot API key.
"""
from __future__ import annotations

# (champion_id, cost, traits) — cost biases synthetic placement strength.
CHAMPIONS = [
    ('TFT17_Aatrox', 1, ['N.O.V.A.', 'Bastion']),
    ('TFT17_Briar', 1, ['Anima', 'Primordian', 'Rogue']),
    ('TFT17_Caitlyn', 1, ['N.O.V.A.', 'Fateweaver']),
    ('TFT17_Chogath', 1, ['Dark Star', 'Brawler']),
    ('TFT17_Ezreal', 1, ['Timebreaker', 'Sniper']),
    ('TFT17_Leona', 1, ['Arbiter', 'Vanguard']),
    ('TFT17_Lissandra', 1, ['Dark Star', 'Shepherd', 'Replicator']),
    ('TFT17_Nasus', 1, ['Space Groove', 'Vanguard']),
    ('TFT17_Poppy', 1, ['Meeple', 'Bastion']),
    ('TFT17_RekSai', 1, ['Primordian', 'Brawler']),
    ('TFT17_Talon', 1, ['Stargazer', 'Rogue']),
    ('TFT17_Teemo', 1, ['Space Groove', 'Shepherd']),
    ('TFT17_TwistedFate', 1, ['Stargazer', 'Fateweaver']),
    ('TFT17_Veigar', 1, ['Meeple', 'Replicator']),
    ('TFT17_Akali', 2, ['N.O.V.A.', 'Marauder']),
    ('TFT17_Belveth', 2, ['Primordian', 'Challenger', 'Marauder']),
    ('TFT17_Gnar', 2, ['Meeple', 'Sniper']),
    ('TFT17_Gragas', 2, ['Psionic', 'Brawler']),
    ('TFT17_Gwen', 2, ['Space Groove', 'Rogue']),
    ('TFT17_Jax', 2, ['Stargazer', 'Bastion']),
    ('TFT17_Jinx', 2, ['Anima', 'Challenger']),
    ('TFT17_IvernMinion', 2, ['Meeple', 'Shepherd', 'Voyager']),
    ('TFT17_Milio', 2, ['Timebreaker', 'Fateweaver']),
    ('TFT17_Mordekaiser', 2, ['Dark Star', 'Conduit', 'Vanguard']),
    ('TFT17_Pantheon', 2, ['Timebreaker', 'Brawler', 'Replicator']),
    ('TFT17_Pyke', 2, ['Psionic', 'Voyager']),
    ('TFT17_Zoe', 2, ['Arbiter', 'Conduit']),
    ('TFT17_Aurora', 3, ['Anima', 'Voyager']),
    ('TFT17_Diana', 3, ['Arbiter', 'Challenger']),
    ('TFT17_Fizz', 3, ['Meeple', 'Rogue']),
    ('TFT17_Illaoi', 3, ['Anima', 'Vanguard', 'Shepherd']),
    ('TFT17_Kaisa', 3, ['Dark Star', 'Rogue']),
    ('TFT17_Lulu', 3, ['Stargazer', 'Replicator']),
    ('TFT17_Maokai', 3, ['N.O.V.A.', 'Brawler']),
    ('TFT17_MissFortune', 3, ['Gun Goddess', 'Choose Trait']),
    ('TFT17_Ornn', 3, ['Space Groove', 'Bastion']),
    ('TFT17_Rhaast', 3, ['Redeemer']),
    ('TFT17_Samira', 3, ['Space Groove', 'Sniper']),
    ('TFT17_Urgot', 3, ['Mecha', 'Brawler', 'Marauder']),
    ('TFT17_Viktor', 3, ['Psionic', 'Conduit']),
    ('TFT17_AurelionSol', 4, ['Mecha', 'Conduit']),
    ('TFT17_Corki', 4, ['Meeple', 'Fateweaver']),
    ('TFT17_Karma', 4, ['Dark Star', 'Voyager']),
    ('TFT17_Kindred', 4, ['N.O.V.A.', 'Challenger']),
    ('TFT17_Leblanc', 4, ['Arbiter', 'Shepherd']),
    ('TFT17_MasterYi', 4, ['Psionic', 'Marauder']),
    ('TFT17_Morgana', 4, ['Dark Lady']),
    ('TFT17_Nami', 4, ['Space Groove', 'Replicator']),
    ('TFT17_Nunu', 4, ['Stargazer', 'Vanguard']),
    ('TFT17_Rammus', 4, ['Meeple', 'Bastion']),
    ('TFT17_Riven', 4, ['Timebreaker', 'Rogue']),
    ('TFT17_TahmKench', 4, ['Oracle', 'Brawler']),
    ('TFT17_Galio', 4, ['Mecha', 'Voyager']),
    ('TFT17_Xayah', 4, ['Stargazer', 'Sniper']),
    ('TFT17_Bard', 5, ['Meeple', 'Conduit']),
    ('TFT17_Blitzcrank', 5, ['Party Animal', 'Space Groove', 'Vanguard']),
    ('TFT17_Fiora', 5, ['Divine Duelist', 'Anima', 'Marauder']),
    ('TFT17_Graves', 5, ['Factory New']),
    ('TFT17_Jhin', 5, ['Dark Star', 'Eradicator', 'Sniper']),
    ('TFT17_Shen', 5, ['Bulwark', 'Bastion']),
    ('TFT17_Sona', 5, ['Commander', 'Psionic', 'Shepherd']),
    ('TFT17_Vex', 5, ['Doomer']),
    ('TFT17_Zed', 5, ['Galaxy Hunter']),
]

ITEMS = [
    'TFT_Item_AdaptiveHelm',
    'TFT_Item_ArchangelsStaff',
    'TFT_Item_Bloodthirster',
    'TFT_Item_BlueBuff',
    'TFT_Item_BrambleVest',
    'TFT_Item_Crownguard',
    'TFT_Item_Deathblade',
    'TFT_Item_CorruptedDeathblade',
    'TFT_Item_DragonsClaw',
    'TFT_Item_GuardianAngel',
    'TFT_Item_SpectralGauntlet',
    'TFT_Item_GargoyleStoneplate',
    'TFT_Item_CorruptedGargoyleStoneplate',
    'TFT_Item_MadredsBloodrazor',
    'TFT_Item_GuinsoosRageblade',
    'TFT_Item_CorruptedGuinsoosRageblade',
    'TFT_Item_UnstableConcoction',
    'TFT_Item_CorruptedHandOfJustice',
    'TFT_Item_HextechGunblade',
    'TFT_Item_InfinityEdge',
    'TFT_Item_CorruptedInfinityEdge',
    'TFT_Item_IonicSpark',
    'TFT_Item_JeweledGauntlet',
    'TFT_Item_CorruptedJeweledGauntlet',
    'TFT_Item_RunaansHurricane',
    'TFT_Item_LastWhisper',
    'TFT_Item_Morellonomicon',
    'TFT_Item_Leviathan',
    'TFT_Item_FrozenHeart',
    'TFT_Item_Quicksilver',
    'TFT_Item_RabadonsDeathcap',
    'TFT_Item_CorruptedRabadonsDeathcap',
    'TFT_Item_RapidFireCannon',
    'TFT_Item_SpearOfShojin',
    'TFT_Item_CorruptedSpearOfShojin',
    'TFT_Item_Redemption',
    'TFT_Item_CorruptedRedemption',
    'TFT_Item_NightHarvester',
    'TFT_Item_SteraksGage',
    'TFT_Item_PowerGauntlet',
    'TFT_Item_RedBuff',
    'TFT_Item_TacticiansRing',
    'TFT_Item_ForceOfNature',
    'TFT_Item_TacticiansScepter',
    'TFT_Item_ThiefsGloves',
    'TFT_Item_TitansResolve',
    'TFT_Item_StatikkShiv',
    'TFT_Item_WarmogsArmor',
    'TFT_Item_CorruptedWarmogsArmor',
    'TFT_Item_CursedBlade',
    'TFT_Item_HextechChestguard',
]

AUGMENTS = [
    'TFT17_Augment_AhriGodAugment',
    'TFT17_Augment_AurelionSolGodAugment',
    'TFT17_Augment_EvelynnGodAugment_BloodPrice',
    'TFT17_Augment_AurelionSolGodAugment_BoonOfResurrection',
    'TFT17_Augment_KayleGodAugment_Scrapper',
    'TFT17_Augment_EkkoGodAugment',
    'TFT17_Augment_EvelynnGodAugment',
    'TFT17_Augment_KayleGodAugment',
    'TFT17_Augment_SorakaGodAugment',
    'TFT17_Augment_ThreshGodAugment',
    'TFT17_Augment_VarusGodAugment_BoonOfStars',
    'TFT17_Augment_YasuoGodAugment_PaintedPower',
    'TFT17_Augment_YasuoGodAugment_GoldenHex',
    'TFT17_Augment_YasuoGodAugment_MoreHexes',
    'TFT17_Augment_AnimaSquad_Commander',
    'TFT17_Augment_ApotheoticForge',
    'TFT17_Augment_NasusCarry',
    'TFT17_Augment_Concentration',
    'TFT17_Augment_PykeCarry',
    'TFT17_Augment_Arbiter_DivineAmendment',
    'TFT17_Augment_ShieldTank_DivinePaladins',
    'TFT17_Augment_PrimordianPrismaticAugment',
    'TFT17_Augment_MordekaiserCarry',
    'TFT17_Augment_InvaderZed',
    'TFT17_Augment_Weightlifting',
    'TFT17_Augment_DarkStar_WhiteHole',
    'TFT17_Augment_Astronaut_KingMeep',
    'TFT17_Augment_DarkStar_NeutronStar',
    'TFT17_Augment_JaxCarry',
    'TFT17_Augment_GragasCarry',
    'TFT17_Augment_ShepherdAugment',
    'TFT17_Augment_LeonaCarry',
    'TFT17_Augment_SnipersNest',
    'TFT17_Augment_AatroxCarry',
    'TFT17_Augment_EmergencySupplies',
    'TFT17_Augment_PoppyCarry',
    'TFT17_Augment_IvernMinionCarry',
    'TFT17_Augment_Timebreaker_Timestream',
    'TFT17_Augment_TourOfTheGalaxy',
]

# Named compositions (trait cores) for the composition entity type.
COMPOSITIONS = [
    'SpaceGroove_Vanguard',
    'Bastion_Meeple',
    'Bastion_N.O.V.A.',
    'Anima_Primordian',
    'Anima_Rogue',
    'Primordian_Rogue',
    'Fateweaver_N.O.V.A.',
    'Brawler_DarkStar',
    'Sniper_Timebreaker',
    'Arbiter_Vanguard',
    'DarkStar_Replicator',
    'DarkStar_Shepherd',
]

TIERS = [
    'IRON',
    'BRONZE',
    'SILVER',
    'GOLD',
    'PLATINUM',
    'DIAMOND',
    'MASTER',
    'GRANDMASTER',
    'CHALLENGER',
]

# Rank ordering for priority queues (lower number = higher priority).
TIER_RANK = {t: i for i, t in enumerate(reversed(TIERS))}

REGIONS = ["NA", "EUW", "KR", "BR"]

# Riot routing: platform host per region, and the regional cluster for match-v1.
REGION_PLATFORM = {"NA": "na1", "EUW": "euw1", "KR": "kr", "BR": "br1"}
REGION_CLUSTER = {"NA": "americas", "EUW": "europe", "KR": "asia", "BR": "americas"}

CHAMPION_IDS = [c[0] for c in CHAMPIONS]
CHAMPION_COST = {c[0]: c[1] for c in CHAMPIONS}
CHAMPION_TRAITS = {c[0]: c[2] for c in CHAMPIONS}

# Every distinct trait, derived from the champion roster.
TRAITS = sorted({t for c in CHAMPIONS for t in c[2]})

SET = "Set17"
SET_NAME = "TFT Set 17"
DEFAULT_PATCH = "17.3"
PATCHES = ["17.1", "17.2", "17.3"]

# Champions favoured in high-elo lobbies (biases synthetic placement).
HIGH_ELO_FAVORITES = ['TFT17_AurelionSol', 'TFT17_Corki', 'TFT17_Karma', 'TFT17_Kindred', 'TFT17_Leblanc', 'TFT17_MasterYi', 'TFT17_Morgana', 'TFT17_Nami']

# One augment flagged as a "trap" — looks good, plays mediocre.
TRAP_AUGMENT = 'TFT17_Augment_AnimaSquad_Commander'

# Silver / Gold / Prismatic tier label per augment (from its asset tier).
AUGMENT_TIERS = {
    'TFT17_Augment_AhriGodAugment': 'gold',
    'TFT17_Augment_AurelionSolGodAugment': 'gold',
    'TFT17_Augment_EvelynnGodAugment_BloodPrice': 'gold',
    'TFT17_Augment_AurelionSolGodAugment_BoonOfResurrection': 'gold',
    'TFT17_Augment_KayleGodAugment_Scrapper': 'gold',
    'TFT17_Augment_EkkoGodAugment': 'gold',
    'TFT17_Augment_EvelynnGodAugment': 'gold',
    'TFT17_Augment_KayleGodAugment': 'gold',
    'TFT17_Augment_SorakaGodAugment': 'gold',
    'TFT17_Augment_ThreshGodAugment': 'gold',
    'TFT17_Augment_VarusGodAugment_BoonOfStars': 'gold',
    'TFT17_Augment_YasuoGodAugment_PaintedPower': 'gold',
    'TFT17_Augment_YasuoGodAugment_GoldenHex': 'silver',
    'TFT17_Augment_YasuoGodAugment_MoreHexes': 'gold',
    'TFT17_Augment_AnimaSquad_Commander': 'gold',
    'TFT17_Augment_ApotheoticForge': 'gold',
    'TFT17_Augment_NasusCarry': 'silver',
    'TFT17_Augment_Concentration': 'gold',
    'TFT17_Augment_PykeCarry': 'gold',
    'TFT17_Augment_Arbiter_DivineAmendment': 'gold',
    'TFT17_Augment_ShieldTank_DivinePaladins': 'gold',
    'TFT17_Augment_PrimordianPrismaticAugment': 'prismatic',
    'TFT17_Augment_MordekaiserCarry': 'gold',
    'TFT17_Augment_InvaderZed': 'gold',
    'TFT17_Augment_Weightlifting': 'gold',
    'TFT17_Augment_DarkStar_WhiteHole': 'gold',
    'TFT17_Augment_Astronaut_KingMeep': 'gold',
    'TFT17_Augment_DarkStar_NeutronStar': 'gold',
    'TFT17_Augment_JaxCarry': 'gold',
    'TFT17_Augment_GragasCarry': 'gold',
    'TFT17_Augment_ShepherdAugment': 'gold',
    'TFT17_Augment_LeonaCarry': 'silver',
    'TFT17_Augment_SnipersNest': 'gold',
    'TFT17_Augment_AatroxCarry': 'silver',
    'TFT17_Augment_EmergencySupplies': 'gold',
    'TFT17_Augment_PoppyCarry': 'silver',
    'TFT17_Augment_IvernMinionCarry': 'gold',
    'TFT17_Augment_Timebreaker_Timestream': 'gold',
    'TFT17_Augment_TourOfTheGalaxy': 'gold',
}

# Broad gameplay category per augment ("god" augments get their own page).
AUGMENT_CATEGORIES = {
    'TFT17_Augment_AhriGodAugment': 'god',
    'TFT17_Augment_AurelionSolGodAugment': 'god',
    'TFT17_Augment_EvelynnGodAugment_BloodPrice': 'god',
    'TFT17_Augment_AurelionSolGodAugment_BoonOfResurrection': 'god',
    'TFT17_Augment_KayleGodAugment_Scrapper': 'god',
    'TFT17_Augment_EkkoGodAugment': 'god',
    'TFT17_Augment_EvelynnGodAugment': 'god',
    'TFT17_Augment_KayleGodAugment': 'god',
    'TFT17_Augment_SorakaGodAugment': 'god',
    'TFT17_Augment_ThreshGodAugment': 'god',
    'TFT17_Augment_VarusGodAugment_BoonOfStars': 'god',
    'TFT17_Augment_YasuoGodAugment_PaintedPower': 'god',
    'TFT17_Augment_YasuoGodAugment_GoldenHex': 'god',
    'TFT17_Augment_YasuoGodAugment_MoreHexes': 'god',
    'TFT17_Augment_AnimaSquad_Commander': 'standard',
    'TFT17_Augment_ApotheoticForge': 'standard',
    'TFT17_Augment_NasusCarry': 'standard',
    'TFT17_Augment_Concentration': 'standard',
    'TFT17_Augment_PykeCarry': 'standard',
    'TFT17_Augment_Arbiter_DivineAmendment': 'standard',
    'TFT17_Augment_ShieldTank_DivinePaladins': 'standard',
    'TFT17_Augment_PrimordianPrismaticAugment': 'standard',
    'TFT17_Augment_MordekaiserCarry': 'standard',
    'TFT17_Augment_InvaderZed': 'standard',
    'TFT17_Augment_Weightlifting': 'standard',
    'TFT17_Augment_DarkStar_WhiteHole': 'standard',
    'TFT17_Augment_Astronaut_KingMeep': 'standard',
    'TFT17_Augment_DarkStar_NeutronStar': 'standard',
    'TFT17_Augment_JaxCarry': 'standard',
    'TFT17_Augment_GragasCarry': 'standard',
    'TFT17_Augment_ShepherdAugment': 'standard',
    'TFT17_Augment_LeonaCarry': 'standard',
    'TFT17_Augment_SnipersNest': 'standard',
    'TFT17_Augment_AatroxCarry': 'standard',
    'TFT17_Augment_EmergencySupplies': 'standard',
    'TFT17_Augment_PoppyCarry': 'standard',
    'TFT17_Augment_IvernMinionCarry': 'standard',
    'TFT17_Augment_Timebreaker_Timestream': 'standard',
    'TFT17_Augment_TourOfTheGalaxy': 'standard',
}

# --------------------------------------------------------------------------- #
# Icon assets (real Community Dragon CDN URLs) + builder payloads the dashboard
# reads from /meta/roster. Champions, items, traits and augments all carry real
# Set 17 artwork.
# --------------------------------------------------------------------------- #
CHAMPION_ICONS = {
    'TFT17_Aatrox': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_aatrox/hud/tft17_aatrox_square.tft_set17.png',
    'TFT17_Briar': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_briar/hud/tft17_briar_square.tft_set17.png',
    'TFT17_Caitlyn': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_caitlyn/hud/tft17_caitlyn_square.tft_set17.png',
    'TFT17_Chogath': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_chogath/hud/tft17_chogath_square.tft_set17.png',
    'TFT17_Ezreal': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_ezreal/hud/tft17_ezreal_square.tft_set17.png',
    'TFT17_Leona': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_leona/hud/tft17_leona_square.tft_set17.png',
    'TFT17_Lissandra': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_lissandra/hud/tft17_lissandra_square.tft_set17.png',
    'TFT17_Nasus': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_nasus/hud/tft17_nasus_square.tft_set17.png',
    'TFT17_Poppy': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_poppy/hud/tft17_poppy_square.tft_set17.png',
    'TFT17_RekSai': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_reksai/hud/tft17_reksai_square.tft_set17.png',
    'TFT17_Talon': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_talon/hud/tft17_talon_square.tft_set17.png',
    'TFT17_Teemo': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_teemo/hud/tft17_teemo_square.tft_set17.png',
    'TFT17_TwistedFate': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_twistedfate/hud/tft17_twistedfate_square.tft_set17.png',
    'TFT17_Veigar': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_veigar/hud/tft17_veigar_square.tft_set17.png',
    'TFT17_Akali': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_akali/hud/tft17_akali_square.tft_set17.png',
    'TFT17_Belveth': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_belveth/hud/tft17_belveth_square.tft_set17.png',
    'TFT17_Gnar': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_gnar/hud/tft17_gnar_square.tft_set17.png',
    'TFT17_Gragas': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_gragas/hud/tft17_gragas_square.tft_set17.png',
    'TFT17_Gwen': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_gwen/hud/tft17_gwen_square.tft_set17.png',
    'TFT17_Jax': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_jax/hud/tft17_jax_square.tft_set17.png',
    'TFT17_Jinx': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_jinx/hud/tft17_jinx_square.tft_set17.png',
    'TFT17_IvernMinion': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_ivernminion/hud/tft17_ivernminion_square.tft_set17.png',
    'TFT17_Milio': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_milio/hud/tft17_milio_square.tft_set17.png',
    'TFT17_Mordekaiser': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_mordekaiser/hud/tft17_mordekaiser_square.tft_set17.png',
    'TFT17_Pantheon': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_pantheon/hud/tft17_pantheon_square.tft_set17.png',
    'TFT17_Pyke': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_pyke/hud/tft17_pyke_square.tft_set17.png',
    'TFT17_Zoe': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_zoe/hud/tft17_zoe_square.tft_set17.png',
    'TFT17_Aurora': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_aurora/hud/tft17_aurora_square.tft_set17.png',
    'TFT17_Diana': 'https://raw.communitydragon.org/latest/game/assets/ux/tft/championsplashes/patching/tft17_diana_teamplanner_splash.tft_set17.png',
    'TFT17_Fizz': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_fizz/hud/tft17_fizz_square.tft_set17.png',
    'TFT17_Illaoi': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_illaoi/hud/tft17_illaoi_square.tft_set17.png',
    'TFT17_Kaisa': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_kaisa/hud/tft17_kaisa_square.tft_set17.png',
    'TFT17_Lulu': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_lulu/hud/tft17_lulu_square.tft_set17.png',
    'TFT17_Maokai': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_maokai/hud/tft17_maokai_square.tft_set17.png',
    'TFT17_MissFortune': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_missfortune/hud/tft17_missfortune_square.tft_set17.png',
    'TFT17_Ornn': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_ornn/hud/tft17_ornn_square.tft_set17.png',
    'TFT17_Rhaast': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_rhaast/hud/tft17_kayn_slay_square.tft_set17.png',
    'TFT17_Samira': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_samira/hud/tft17_samira_square.tft_set17.png',
    'TFT17_Urgot': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_urgot/hud/tft17_urgot_square.tft_set17.png',
    'TFT17_Viktor': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_viktor/hud/tft17_viktor_square.tft_set17.png',
    'TFT17_AurelionSol': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_aurelionsol/hud/tft17_aurelionsol_square.tft_set17.png',
    'TFT17_Corki': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_corki/hud/tft17_corki_square.tft_set17.png',
    'TFT17_Karma': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_karma/hud/tft17_karma_square.tft_set17.png',
    'TFT17_Kindred': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_kindred/hud/tft17_kindred_square.tft_set17.png',
    'TFT17_Leblanc': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_leblanc/hud/tft17_leblanc_square.tft_set17.png',
    'TFT17_MasterYi': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_masteryi/hud/tft17_masteryi_square.tft_set17.png',
    'TFT17_Morgana': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_morgana/hud/tft17_morgana_square.tft_set17.png',
    'TFT17_Nami': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_nami/hud/tft17_nami_square.tft_set17.png',
    'TFT17_Nunu': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_nunu/hud/tft17_nunu_square.tft_set17.png',
    'TFT17_Rammus': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_rammus/hud/tft17_rammus_square.tft_set17.png',
    'TFT17_Riven': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_riven/hud/tft17_riven_square.tft_set17.png',
    'TFT17_TahmKench': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_tahmkench/hud/tft17_tahmkench_square.tft_set17.png',
    'TFT17_Galio': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_galio/hud/tft17_galio_square.tft_set17.png',
    'TFT17_Xayah': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_xayah/hud/tft17_xayah_square.tft_set17.png',
    'TFT17_Bard': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_bard/hud/tft17_bard_square.tft_set17.png',
    'TFT17_Blitzcrank': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_blitzcrank/hud/tft17_blitzcrank_square.tft_set17.png',
    'TFT17_Fiora': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_fiora/hud/tft17_fiora_square.tft_set17.png',
    'TFT17_Graves': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_graves/hud/tft17_graves_square.tft_set17.png',
    'TFT17_Jhin': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_jhin/hud/tft17_jhin_square.tft_set17.png',
    'TFT17_Shen': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_shen/hud/tft17_shen_square.tft_set17.png',
    'TFT17_Sona': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_sona/hud/tft17_sona_square.tft_set17.png',
    'TFT17_Vex': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_vex/hud/tft17_vex_square.tft_set17.png',
    'TFT17_Zed': 'https://raw.communitydragon.org/latest/game/assets/characters/tft17_zed/hud/tft17_zed_square.tft_set17.png',
}

BUILDER_ITEMS = [
    {"id": 'TFT_Item_AdaptiveHelm', "name": 'Adaptive Helm', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_adaptivehelm.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_ArchangelsStaff', "name": "Archangel's Staff", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_archangelsstaff.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_Bloodthirster', "name": 'Bloodthirster', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_bloodthirster.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_BlueBuff', "name": 'Blue Buff', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_bluebuff.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_BrambleVest', "name": 'Bramble Vest', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_bramblevest.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_Crownguard', "name": 'Crownguard', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_crownguard.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_Deathblade', "name": 'Deathblade', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_deathblade.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_CorruptedDeathblade', "name": 'Deathblade', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_deathblade.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_DragonsClaw', "name": "Dragon's Claw", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_dragonsclaw.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_GuardianAngel', "name": 'Edge of Night', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_guardianangel.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_SpectralGauntlet', "name": 'Evenshroud', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_spectralgauntlet.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_GargoyleStoneplate', "name": 'Gargoyle Stoneplate', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_gargoylestoneplate.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_CorruptedGargoyleStoneplate', "name": 'Gargoyle Stoneplate', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_gargoylestoneplate.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_MadredsBloodrazor', "name": 'Giant Slayer', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_madredsbloodrazor.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_GuinsoosRageblade', "name": "Guinsoo's Rageblade", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_guinsoosrageblade.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_CorruptedGuinsoosRageblade', "name": "Guinsoo's Rageblade", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_guinsoosrageblade.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_UnstableConcoction', "name": 'Hand Of Justice', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_unstableconcoction.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_CorruptedHandOfJustice', "name": 'Hand Of Justice', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_unstableconcoction.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_HextechGunblade', "name": 'Hextech Gunblade', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_hextechgunblade.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_InfinityEdge', "name": 'Infinity Edge', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_infinityedge.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_CorruptedInfinityEdge', "name": 'Infinity Edge', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_infinityedge.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_IonicSpark', "name": 'Ionic Spark', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_ionicspark.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_JeweledGauntlet', "name": 'Jeweled Gauntlet', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_jeweledgauntlet.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_CorruptedJeweledGauntlet', "name": 'Jeweled Gauntlet', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_jeweledgauntlet.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_RunaansHurricane', "name": "Kraken's Fury", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_krakenslayer.png', "kind": "completed"},
    {"id": 'TFT_Item_LastWhisper', "name": 'Last Whisper', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_lastwhisper.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_Morellonomicon', "name": 'Morellonomicon', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_morellonomicon.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_Leviathan', "name": "Nashor's Tooth", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_leviathan.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_FrozenHeart', "name": "Protector's Vow", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_frozenheart.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_Quicksilver', "name": 'Quicksilver', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_quicksilver.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_RabadonsDeathcap', "name": "Rabadon's Deathcap", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_rabadonsdeathcap.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_CorruptedRabadonsDeathcap', "name": "Rabadon's Deathcap", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_rabadonsdeathcap.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_RapidFireCannon', "name": 'Red Buff', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_rapidfirecannon.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_SpearOfShojin', "name": 'Spear of Shojin', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_spearofshojin.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_CorruptedSpearOfShojin', "name": 'Spear of Shojin', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_spearofshojin.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_Redemption', "name": 'Spirit Visage', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_spiritvisagerr.png', "kind": "completed"},
    {"id": 'TFT_Item_CorruptedRedemption', "name": 'Spirit Visage', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_spiritvisagerr.png', "kind": "completed"},
    {"id": 'TFT_Item_NightHarvester', "name": 'Steadfast Heart', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_nightharvester.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_SteraksGage', "name": "Sterak's Gage", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_steraksgage.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_PowerGauntlet', "name": "Striker's Flail", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_powergauntlet.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_RedBuff', "name": 'Sunfire Cape', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_redbuff.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_TacticiansRing', "name": "Tactician's Cape", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_tacticiansring.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_ForceOfNature', "name": "Tactician's Crown", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_forceofnature.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_TacticiansScepter', "name": "Tactician's Shield", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_tacticiansscepter.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_ThiefsGloves', "name": "Thief's Gloves", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_thiefsgloves.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_TitansResolve', "name": "Titan's Resolve", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_titansresolve.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_StatikkShiv', "name": 'Void Staff', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_voidstaff.png', "kind": "completed"},
    {"id": 'TFT_Item_WarmogsArmor', "name": "Warmog's Armor", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_warmogsarmor.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_CorruptedWarmogsArmor', "name": "Warmog's Armor", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/items/hexcore/tft_item_warmogsarmor.tft_set13.png', "kind": "completed"},
    {"id": 'TFT_Item_CursedBlade', "name": 'tft_item_name_CursedBlade', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/particles/tft/tft_item_cursedblade.png', "kind": "completed"},
    {"id": 'TFT_Item_HextechChestguard', "name": 'tft_item_name_HextechChestguard', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/particles/tft/tft_item_hextechchestguard.png', "kind": "completed"},
]

TRAITS_DATA = [
    {"name": 'Anima', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_animatech.tft_set17.png', "breakpoints": [3, 6]},
    {"name": 'Arbiter', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_arbiter.tft_set17.png', "breakpoints": [2, 3]},
    {"name": 'Bastion', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_9_bastion.png', "breakpoints": [2, 4, 6]},
    {"name": 'Brawler', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_brawler.png', "breakpoints": [2, 4, 6]},
    {"name": 'Bulwark', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_bulwark.tft_set17.png', "breakpoints": [1]},
    {"name": 'Challenger', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_challenger.tft_set17.png', "breakpoints": [2, 3, 4, 5]},
    {"name": 'Choose Trait', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_missfortuneundetermindedtrait.tft_set17.png', "breakpoints": []},
    {"name": 'Commander', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_commander.tft_set17.png', "breakpoints": [1]},
    {"name": 'Conduit', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_channeler.tft_set17.png', "breakpoints": [2, 3, 4, 5]},
    {"name": 'Dark Lady', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_darklady.tft_set17.png', "breakpoints": [1]},
    {"name": 'Dark Star', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_darkstar.tft_set17.png', "breakpoints": [2, 4, 6, 9]},
    {"name": 'Divine Duelist', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_divineduelist.tft_set17.png', "breakpoints": [1]},
    {"name": 'Doomer', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_doomer.tft_set17.png', "breakpoints": [1]},
    {"name": 'Eradicator', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_singularity.tft_set17.png', "breakpoints": [1]},
    {"name": 'Factory New', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_factorynew.tft_set17.png', "breakpoints": [1]},
    {"name": 'Fateweaver', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_fateweaver.tft_set17.png', "breakpoints": [2, 4]},
    {"name": 'Galaxy Hunter', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_galaxyhunter.tft_set17.png', "breakpoints": [1]},
    {"name": 'Gun Goddess', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_gungoddess.tft_set17.png', "breakpoints": [1]},
    {"name": 'Marauder', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_16_slayer.png', "breakpoints": [2, 4, 6]},
    {"name": 'Mecha', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_mecha.tft_set17.png', "breakpoints": [3, 4, 6]},
    {"name": 'Meeple', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_astronaut.tft_set17.png', "breakpoints": [3, 5, 7, 10]},
    {"name": 'N.O.V.A.', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_nova.tft_set17.png', "breakpoints": [2, 5]},
    {"name": 'Oracle', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_12_arcana.tft_set12.png', "breakpoints": [1]},
    {"name": 'Party Animal', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_partyanimal.tft_set17.png', "breakpoints": [1]},
    {"name": 'Primordian', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_primordian.tft_set17.png', "breakpoints": [2, 3]},
    {"name": 'Psionic', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_psyops.tft_set17.png', "breakpoints": [2, 4]},
    {"name": 'Redeemer', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_redeemer.tft_set17.png', "breakpoints": [1]},
    {"name": 'Replicator', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_replicator.tft_set17.png', "breakpoints": [2, 4]},
    {"name": 'Rogue', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_rogue.tft_set17.png', "breakpoints": [2, 3, 4, 5]},
    {"name": 'Shepherd', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_shepherd.tft_set17.png', "breakpoints": [3, 5, 7]},
    {"name": 'Sniper', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_6_sniper.png', "breakpoints": [2, 3, 4]},
    {"name": 'Space Groove', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_spacegroove.tft_set17.png', "breakpoints": [1, 3, 5, 7, 10]},
    {"name": 'Stargazer', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_stargazer.tft_set17.png', "breakpoints": [3, 4, 5, 6]},
    {"name": 'Stargazer', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_stargazer.tft_set17.png', "breakpoints": [3]},
    {"name": 'Stargazer', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_stargazer.tft_set17.png', "breakpoints": [3, 5, 7]},
    {"name": 'Stargazer', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_stargazer.tft_set17.png', "breakpoints": [3, 5, 7]},
    {"name": 'Stargazer', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_stargazer.tft_set17.png', "breakpoints": [3]},
    {"name": 'Stargazer', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_stargazer.tft_set17.png', "breakpoints": [3, 5]},
    {"name": 'Stargazer', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_stargazer.tft_set17.png', "breakpoints": [3, 4, 5, 6, 7, 8, 9, 10, 11]},
    {"name": 'Stargazer', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_stargazer.tft_set17.png', "breakpoints": [3, 5, 7, 8, 9, 10]},
    {"name": 'Timebreaker', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_timebreaker.tft_set17.png', "breakpoints": [2, 3, 4]},
    {"name": 'Vanguard', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_12_vanguard.tft_set12.png', "breakpoints": [2, 4, 6]},
    {"name": 'Voyager', "icon": 'https://raw.communitydragon.org/latest/game/assets/ux/traiticons/trait_icon_17_voyager.tft_set17.png', "breakpoints": [2, 3, 4, 5, 6]},
]

BUILDER_AUGMENTS = [
    {"id": 'TFT17_Augment_AhriGodAugment', "name": "Ahri's Boon", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/godaugmentahri_ii.tft_set17.png', "tier": 'gold', "category": 'god'},
    {"id": 'TFT17_Augment_AurelionSolGodAugment', "name": "Aurelion Sol's Boon", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/godaugmentaurelionsol_ii.tft_set17.png', "tier": 'gold', "category": 'god'},
    {"id": 'TFT17_Augment_EvelynnGodAugment_BloodPrice', "name": 'Blood Price', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/missing-t2.png', "tier": 'gold', "category": 'god'},
    {"id": 'TFT17_Augment_AurelionSolGodAugment_BoonOfResurrection', "name": 'Boon of Resurrection', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/missing-t2.png', "tier": 'gold', "category": 'god'},
    {"id": 'TFT17_Augment_KayleGodAugment_Scrapper', "name": 'Boon of the Scrapper', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/missing-t2.png', "tier": 'gold', "category": 'god'},
    {"id": 'TFT17_Augment_EkkoGodAugment', "name": "Ekko's Boon", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/godaugmentekko_ii.tft_set17.png', "tier": 'gold', "category": 'god'},
    {"id": 'TFT17_Augment_EvelynnGodAugment', "name": "Evelynn's Boon", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/godaugmentevelynn_ii.tft_set17.png', "tier": 'gold', "category": 'god'},
    {"id": 'TFT17_Augment_KayleGodAugment', "name": "Kayle's Boon", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/godaugmentkayle_ii.tft_set17.png', "tier": 'gold', "category": 'god'},
    {"id": 'TFT17_Augment_SorakaGodAugment', "name": "Soraka's Boon", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/godaugmentsoraka_ii.tft_set17.png', "tier": 'gold', "category": 'god'},
    {"id": 'TFT17_Augment_ThreshGodAugment', "name": "Thresh's Boon", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/godaugmentthresh_ii.tft_set17.png', "tier": 'gold', "category": 'god'},
    {"id": 'TFT17_Augment_VarusGodAugment_BoonOfStars', "name": "Varus's Boon", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/godaugmentvarus_ii.tft_set17.png', "tier": 'gold', "category": 'god'},
    {"id": 'TFT17_Augment_YasuoGodAugment_PaintedPower', "name": "Yasuo's Boon", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/godaugmentyasuo_ii.tft_set17.png', "tier": 'gold', "category": 'god'},
    {"id": 'TFT17_Augment_YasuoGodAugment_GoldenHex', "name": "Yasuo's Golden Hex", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/findyourcenter_i.tft_set12.png', "tier": 'silver', "category": 'god'},
    {"id": 'TFT17_Augment_YasuoGodAugment_MoreHexes', "name": "Yasuo's Share The Spotlight", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/sharespotlight2.png', "tier": 'gold', "category": 'god'},
    {"id": 'TFT17_Augment_AnimaSquad_Commander', "name": 'Anima Commander', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/animacommander_ii.tft_set17.png', "tier": 'gold', "category": 'standard'},
    {"id": 'TFT17_Augment_ApotheoticForge', "name": 'Apotheotic Forge', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/job_s-done-ii.png', "tier": 'gold', "category": 'standard'},
    {"id": 'TFT17_Augment_NasusCarry', "name": 'Bonk!', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/bonk_i.tft_set17.png', "tier": 'silver', "category": 'standard'},
    {"id": 'TFT17_Augment_Concentration', "name": 'Concentration', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/concentration_ii.tft_17_3.png', "tier": 'gold', "category": 'standard'},
    {"id": 'TFT17_Augment_PykeCarry', "name": 'Contract Killer', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/contractkiller_ii.tft_set17.png', "tier": 'gold', "category": 'standard'},
    {"id": 'TFT17_Augment_Arbiter_DivineAmendment', "name": 'Divine Amendment', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/divineamendment_ii.tft_set17_postlaunchaugments.png', "tier": 'gold', "category": 'standard'},
    {"id": 'TFT17_Augment_ShieldTank_DivinePaladins', "name": 'Divine Paladins', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/divine-paladins.tft_set17.png', "tier": 'gold', "category": 'standard'},
    {"id": 'TFT17_Augment_PrimordianPrismaticAugment', "name": 'Heart of the Swarm', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/heartoftheswarm_iii.tft_set17_postlaunchaugments.png', "tier": 'prismatic', "category": 'standard'},
    {"id": 'TFT17_Augment_MordekaiserCarry', "name": 'Heat Death', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/starconqueror_ii.tft_set17.png', "tier": 'gold', "category": 'standard'},
    {"id": 'TFT17_Augment_InvaderZed', "name": 'Invader Zed', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/invaderzed_ii.tft_set17.png', "tier": 'gold', "category": 'standard'},
    {"id": 'TFT17_Augment_Weightlifting', "name": 'Lift Off', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/liftingcompetition_ii.tft_set17.png', "tier": 'gold', "category": 'standard'},
    {"id": 'TFT17_Augment_DarkStar_WhiteHole', "name": 'Loot Singularity', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/whitehole_ii.tft_17_3.png', "tier": 'gold', "category": 'standard'},
    {"id": 'TFT17_Augment_Astronaut_KingMeep', "name": 'Meep King', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/missing-t2.png', "tier": 'gold', "category": 'standard'},
    {"id": 'TFT17_Augment_DarkStar_NeutronStar', "name": 'Neutron Star', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/missing-t3.png', "tier": 'gold', "category": 'standard'},
    {"id": 'TFT17_Augment_JaxCarry', "name": 'Reach for the Stars', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/reachforthestars_ii.tft_set17.png', "tier": 'gold', "category": 'standard'},
    {"id": 'TFT17_Augment_GragasCarry', "name": 'Self Destruct', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/selfdestruct_ii.tft_set17.png', "tier": 'gold', "category": 'standard'},
    {"id": 'TFT17_Augment_ShepherdAugment', "name": "Shepherd's Song", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/shepherdssong_ii.tft_set17.png', "tier": 'gold', "category": 'standard'},
    {"id": 'TFT17_Augment_LeonaCarry', "name": 'Shieldmaiden', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/leonahero_i.tft_set17_postlaunchaugments.png', "tier": 'silver', "category": 'standard'},
    {"id": 'TFT17_Augment_SnipersNest', "name": "Sniper's Nest", "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/snipersnest2.png', "tier": 'gold', "category": 'standard'},
    {"id": 'TFT17_Augment_AatroxCarry', "name": 'Stellar Combo', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/aatroxhero_i.tft_set17.png', "tier": 'silver', "category": 'standard'},
    {"id": 'TFT17_Augment_EmergencySupplies', "name": 'TFT17_Augment_Psionic_EmergencySupplies_Name', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/emergencysupplies_ii.tft_17_3.png', "tier": 'gold', "category": 'standard'},
    {"id": 'TFT17_Augment_PoppyCarry', "name": 'Termeepnal Velocity', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/poppyhero_i.tft_set17.png', "tier": 'silver', "category": 'standard'},
    {"id": 'TFT17_Augment_IvernMinionCarry', "name": 'The Big Bang', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/meepspace9_ii.tft_set17.png', "tier": 'gold', "category": 'standard'},
    {"id": 'TFT17_Augment_Timebreaker_Timestream', "name": 'Timestream', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/timestream_ii.tft_set17_postlaunchaugments.png', "tier": 'gold', "category": 'standard'},
    {"id": 'TFT17_Augment_TourOfTheGalaxy', "name": 'Tour of the Galaxy', "icon": 'https://raw.communitydragon.org/latest/game/assets/maps/tft/icons/augments/hexcore/tourofthegalaxy_ii.tft_set17_postlaunchaugments.png', "tier": 'gold', "category": 'standard'},
]
